DROP DATABASE icecream_shop;
CREATE DATABASE IF NOT EXISTS icecream_shop;
SHOW DATABASES;
USE icecream_shop;
SHOW TABLES;
DESCRIBE orders;
SELECT * FROM orders;

SELECT 
	CONSTRAINT_NAME,
	TABLE_NAME,
	COLUMN_NAME,
	REFERENCED_TABLE_NAME,
	REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_NAME IS NOT NULL
AND TABLE_SCHEMA = 'icecream_shop';